### ISSUE TITLE
Nach upgrade auf js-controller> Warunungen wg ack-flag

### ISSUE THREAD

**Issue by OstfrieseUnterwegs** [Pittini/iobroker-Fensterauswertung#34]
Nach Upgrade jede Menge Warnungen wegen fehlendem ack-flag. Z.B.

`Read-only state "javascript.0.FensterUeberwachung.RoomsWithOpenings" has been written without ack-flag with value "Schlafzimmer 1 offenes Fenster<br>"
`

**Comment by Pittini** [comment]
Fixed with 1.6.12, please check.

**Comment by OstfrieseUnterwegs** [comment]
In function WriteMessageLog(msg), row 419, ack still missing

**Comment by Pittini** [comment]
Thanks. Fixed, without new version number.
